paths:
  csv:
    ras_dir: 'data/csv/ras'
    geo_dir: 'data/csv/geo'
  pt:
    train: 'data/pt/train_prepared.pt'
    validation: 'data/pt/validation_prepared.pt'
    test: 'data/pt/test_prepared.pt'
    normalization: 'data/pt/normalization_scales.pt'
  figure_dir: 'out'

data:
  max_geo_points: 481

training:
  seed: 2032
  epochs: 30
  pretrain_epochs: 0
  learning_rate: 1.0e-3
  cases_per_batch: 8
  points_per_case: 512
  gradient_clip: 1.0

loss_weights:
  mass: 10.0
  momentum: 1.0e-6

monitor:
  time_step: 24
  time_batch: 24
  final_test_time_step: 1

plot:
  contour_levels: 8

fvm2:
  seed: 2032
  epochs: 200
  cases_per_batch: 8
  points_per_case: 64 # 采样点
  num_threads: 4
  manning_n: 0.020816
  learning_rate: 1.0e-3
  min_learning_rate: 2.0e-4
  weight_decay: 1.0e-5
  output_path: '../out/train_fvm'
  val_time_step: 24
  val_time_batch: 6